### ISSUE TITLE
udiskie includes internal HDD

### ISSUE THREAD

**Issue by rieje** [coldfix/udiskie#146]
I was under the assumption that udiskie should only include external HDDs, since it never showed my internal drives (this is of course more desirable). However, I recently added an internal HDD that is Btrfs RAID 1 on LVM on LUKS and it is listed by udiskie as a drive that I can lock and dismount. 

I want to prevent udiskie from considering this drive as an external HDD because I run `udiskie-umount --all && systemctl poweroff --ignore-inhibitors` before shutting down the system and it exits with code 1 (thus preventing system shutdown). I have already added a /etc/crypttab entry and a /etc/fstab entry which successfully automounts the drive and decrypts it on boot.

I'm not too experienced with Linux (I'm using Arch). Please let me know how to diagnose this issue. Thanks.

**Comment by coldfix** [comment]
Hi,

thanks for your report!

First off, if you have problems with a specific device, there is an easy way to blacklist it: just add to your `~/.config/udiskie/udiskie.yml` a rule as follows:

```yaml
device_config:
  - id_uuid: UUID
    ignore: true
```

where you replace the UUID of the device as reported by `udiskie-info -o '{device_presentation}: {id_uuid}' -a`.

Furthermore, to shutdown your system, you probably don't need `udiskie-umount` at all, since the system should do this anyway. If you really want to do it, use `udiskie-umount --all; systemctl poweroff ...`, i.e. in series, but not necessarily requiring udiskie to succeed.

Next, to diagnose the problem. Can you start udiskie with `udiskie -vtA` (verbose, tray, no automount), and watch/post the ignore filters applied for your device. Also show the output of `udisksctl info /dev/sda1` or whatever your device is, specifically `HintSystem`.

**Comment by coldfix** [comment]
(sorry, config file name was incorrected, fixed now)

**Comment by rieje** [comment]
Sorry for the late response. I followed your advice but was unable to make udiskie ignore the device. When I left click the icon, it still shows my device as "/dev/sdd WDC WD80..." and hovering over it allows me to attempt to lock /dev/sdd1 or eject it (both of which will not work of course)--/dev/sdd1 is LUKS-encrypted partition which has 3 logical volumes (via LVM), 2 of which are RAID 1 devices.

Following your advice the output of `udiskie-info -o '{id_uuid}' /dev/sdd1` is `d51a8388-acf2-458a-8a9c-c6d0d76221d8`, therefore [this](https://ptpb.pw/APzXF1OZcpZ69UU-kOuSO_chUCbX.yml) is my `~/.config/udiskie/config.yml`.

The relevant output of `udiskie -vtA`:

    DEBUG [2017-10-10 16:53:09,207] udiskie.config: IgnoreDevice(match={'is_block': False}, ignore=True) used for /org/freedesktop/UDisks2/drives/WDC_WD5000AAKS_00A7B0_WD_WMASY0366244
    DEBUG [2017-10-10 16:53:09,207] udiskie.config: IgnoreDevice(match={'is_block': False}, ignore=True) used for /org/freedesktop/UDisks2/drives/WDC_WD80EFAX_68LHPN0_7SGD5UXC

The output of `udisksctl info -b /dev/sdd1` is shown [here](https://ptpb.pw/ANlg0pVUpOGkugdDbaetxhR2AQCM).

**Comment by coldfix** [comment]
Please dedent the `device_config` key to the same level as `program_options`

**Comment by rieje** [comment]
Ahh, ok. It no longer shows the option to lock /dev/sdd1 now but /dev/sdd entry is still listed and when hovered over, there is an option to eject it (it's the only option now).

**Comment by coldfix** [comment]
Ok, you can find out identifying characteristics of `/dev/sdd` (i.e. `id_uuid`, `device_id`, or simply `device_file`) using `udiskie-info`; and ignore that with the device_config rule. In the simplest case:

```yaml
device_config:
  - device_file: /dev/sdd
    ignore: true
```

**Comment by rieje** [comment]
Thanks--the following works:

    device_config:
      - device_file: /dev/sdd
        ignore: true 
      - id_uuid: d51a8388-acf2-458a-8a9c-c6d0d76221d8
        ignore: true

I'm not sure why by default it's shown on udiskie and I need these settings. Also I need both attributes (`device_file` and `id_uuid`) to be ignored--commenting out one of them will still show the option to either lock the device or eject it.

**Comment by coldfix** [comment]
You need both setting because partition (/dev/sdd1) and partition table (/dev/sdd) are separate block devices. As for why you need them at all: udiskie uses the information (HintSystem) passed along from udisks which apparently did not do a good job at guessing in your particular case. Things might improve, when I add support for LVM devices probably by the beginning of next year.

**Comment by rieje** [comment]
I see. By the way, even though udiskie no longer shows the device now,

`# udiskie-umount --all`:

> failed to lock /org/freedesktop/UDisks2/block_devices/sdd1: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error locking /dev/dm-2 (/dev/sdd1): Failed to deactivate device: Device or resource busy

`$ udiskie-umount --all`:
> not locking /org/freedesktop/UDisks2/block_devices/sdd1: unhandled device

I would think udiskie would ignore /dev/sdd1 and the commands wouldn't even consider /dev/sdd1 as something to unmount, thereby exit code would be 0 and guaranteeing `udiskie-umount --all && systemctl poweroff --ignore-inhibitors` works.

Will try using `;` instead of `&&` before doing `systemctl poweroff` like you said in your first post and if that still doesn't work then I'll just remove the udiskie command altogether.

**Comment by coldfix** [comment]
Weird, that should not happen and is probably a bug on udiskie side.

Can you show the output of `udiskie-umount --all -v` or `udiskie-mount -v`?

Best and thanks a lot for your effort, Thomas

**Comment by rieje** [comment]
[Output](https://ptpb.pw/AEHUXUo1AsbclRBxNFkUJN0tCIVv) of `udiskie-umount --all -v`. 

who's thomas

**Comment by coldfix** [comment]
Oh, very sorry! I didn't notice you had responded and now the pastebin is expired. Can you repost? (it's best to attach directly here, so it doesn't expire)
